public static void DiseaseTest(CoopDiseaseData d);
public static IntPtr GetPointer(CoopDiseaseData d, bool ignoreError = false);
if (d != null && CoopDiseaseExternal.diseasePointers != null && d.id < CoopDiseaseExternal.diseasePointers.Length);
if (!ignoreError);
public static IntPtr GetPointer(CoopLocalDiseaseData ld);
public static IntPtr GetPointer(CoopCountryData c);
public static void SetDiseases(CoopDiseaseData d);
if (CoopDiseaseExternal.diseaseHandles != null);
foreach (GCHandle gchandle in CoopDiseaseExternal.diseaseHandles);
if (gchandle.IsAllocated);
for (int j = 0; j < d.Length; j++);
public static void SetCountries(CoopCountryData c);
if (CoopDiseaseExternal.countryHandles != null);
foreach (GCHandle gchandle in CoopDiseaseExternal.countryHandles);
if (gchandle.IsAllocated);
for (int j = 0; j < c.Length; j++);
public static void SetLocalDiseases(CoopLocalDiseaseData ld);
if (CoopDiseaseExternal.localDiseaseHandles != null);
foreach (GCHandle gchandle in CoopDiseaseExternal.localDiseaseHandles);
if (gchandle.IsAllocated);
for (int j = 0; j < ld.Length; j++);
public static void DiseaseUpdate(CoopDiseaseData d, long totalPop);
public static void DiseasePostLocalUpdate(CoopDiseaseData dat, long totalPop, long infectedPop, long deadPop);
public static void DiseaseInitialise(CoopDiseaseData d);
public static int GetGeneticDriftCost(CoopDiseaseData d, int cost);
if (pointer == IntPtr.Zero);
public static bool CheckEvo(CoopDiseaseData d);
public static void SetEvoPoints(CoopDiseaseData d, int points);
if (pointer == IntPtr.Zero);
public static bool CheckTurn(CoopDiseaseData d);
public static void SetTurn(CoopDiseaseData d, int turn);
public static void Cleanup();
if (CoopDiseaseExternal.diseaseHandles != null);
foreach (GCHandle gchandle in CoopDiseaseExternal.diseaseHandles);
if (gchandle.IsAllocated);
if (CoopDiseaseExternal.countryHandles != null);
foreach (GCHandle gchandle2 in CoopDiseaseExternal.countryHandles);
if (gchandle2.IsAllocated);
if (CoopDiseaseExternal.localDiseaseHandles != null);
foreach (GCHandle gchandle3 in CoopDiseaseExternal.localDiseaseHandles);
if (gchandle3.IsAllocated);