public static void DiseaseTest(SPDiseaseData d);
public static void DiseaseUpdate(SPDiseaseData d);
public static void DiseasePrepareTotals(SPDiseaseData d);
public static void DiseaseCountryUpdate(SPDiseaseData d, SPCountryData c, SPLocalDiseaseData ld);
public static void DiseasePostCountryUpdate(SPDiseaseData dat, int countryCount, long totalPop);
public static void DiseasePostLocalUpdate(SPDiseaseData dat, long totalPop);
public static void DiseaseInitialise(SPDiseaseData d);
public static int GetGeneticDriftCost(SPDiseaseData d, int cost);
public static bool CheckEvo(SPDiseaseData d);
public static void SetEvoPoints(SPDiseaseData d, int points);
public static bool CheckTurn(SPDiseaseData d);
public static void SetTurn(SPDiseaseData d, int turn);
public static void DiseaseUpdate_Cure(SPDiseaseData d);
public static void DiseasePrepareTotals_Cure(SPDiseaseData d);
public static void DiseaseCountryUpdate_Cure(SPDiseaseData d, SPCountryData c, SPLocalDiseaseData ld);
public static void DiseasePostCountryUpdate_Cure(SPDiseaseData dat, int countryCount, long totalPop);
public static void DiseasePostLocalUpdate_Cure(SPDiseaseData dat, int countryCount, long totalPop);
public static void DiseasePostLocalUpdate_Cure2(SPDiseaseData dat, int countryCount, long totalPop);
public static void DiseaseUpdate_FakeNews(SPDiseaseData d);
public static void DiseasePrepareTotals_FakeNews(SPDiseaseData d);
public static void DiseaseCountryUpdate_FakeNews(SPDiseaseData d, SPCountryData c, SPLocalDiseaseData ld);
public static void DiseasePostCountryUpdate_FakeNews(SPDiseaseData dat, int countryCount, long totalPop);
public static void DiseasePostLocalUpdate_FakeNews(SPDiseaseData dat, long totalPop);
public static void DiseaseUpdate_Vampire(SPDiseaseData d);
public static void DiseasePrepareTotals_Vampire(SPDiseaseData d);
public static void DiseaseCountryUpdate_Vampire(SPDiseaseData d, SPCountryData c, SPLocalDiseaseData ld);
public static void DiseasePostCountryUpdate_Vampire(SPDiseaseData dat, int countryCount, long totalPop);
public static void DiseasePostLocalUpdate_Vampire(SPDiseaseData dat, long totalPop);