public static void LocalDiseaseTest(SPLocalDiseaseData d);
public static void LocalDiseaseUpdate(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static void LocalDiseaseUpdateSecond(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static void LocalSimianUpdateSecond(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d, int hordeMoving);
public static void LocalDiseaseApeLabUpdate(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d, int masterLab);
public static void LocalDiseaseApeActivityUpdate(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d, int actual_ape_H2I);
public static void LocalDiseaseApeRampageUpdate(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static bool SeaTransfer(SPDiseaseData d, SPLocalDiseaseData ld, SPCountryData source, SPLocalDiseaseData td, SPCountryData destination);
public static bool AirTransfer(SPDiseaseData d, SPLocalDiseaseData ld, SPCountryData source, SPLocalDiseaseData td, SPCountryData destination);
public static bool LandTransfer(SPDiseaseData d, SPLocalDiseaseData ld, SPCountryData source, SPLocalDiseaseData td, SPCountryData destination, int landRoutesMult);
public static bool ZombieTransfer(SPDiseaseData d, SPLocalDiseaseData ld, SPCountryData source, SPLocalDiseaseData td, SPCountryData destination);
public static bool ApeTransfer(SPDiseaseData d, SPLocalDiseaseData ld, SPCountryData source, SPLocalDiseaseData td, SPCountryData destination);
public static void LocalDiseaseUpdate_Cure(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static void LocalDiseaseUpdate_Cure2(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static void LocalDiseaseUpdate_FakeNews(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static void LocalDiseaseUpdate_Vampire(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static void LocalDiseaseUpdateSecond_Vampire(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static void LocalDiseaseUpdateThird_Vampire(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d);
public static void LocalDiseaseUpdateFourth_Vampire(SPLocalDiseaseData ld, SPCountryData c, SPDiseaseData d, float h1, float h2, float h3);
public static bool SeaTransfer_Vampire(SPDiseaseData d, SPLocalDiseaseData ld, SPCountryData source, SPLocalDiseaseData td, SPCountryData destination);
public static bool AirTransfer_Vampire(SPDiseaseData d, SPLocalDiseaseData ld, SPCountryData source, SPLocalDiseaseData td, SPCountryData destination);
public static bool LandTransfer_Vampire(SPDiseaseData d, SPLocalDiseaseData ld, SPCountryData source, SPLocalDiseaseData td, SPCountryData destination, int landRoutesMult);